/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';
import { IPvaChatConnectorData } from './pva-chat-connector.data';
import { IPvaChatConnectorConfig, IPvaChatConnectorProps } from './pva-chat-connector.props.autogenerated';

export interface IPvaChatConnectorViewProps extends IPvaChatConnectorProps<IPvaChatConnectorData> {
    config: IPvaChatConnectorConfig;
}

/**
 * PvaChatConnector component
 * @extends {React.PureComponent<IPvaChatConnectorProps<IPvaChatConnectorData>>}
 */
class PvaChatConnector extends React.PureComponent<IPvaChatConnectorProps<IPvaChatConnectorData>> {
    // Loads CDN version of Botframework-Webchat library
    public componentDidMount(): void {
        const url = this.props.config.botFrameworkCDNURL || this.props.context.app.config.pvaChatConnectorBotFrameworkCDNURL;
        const script = document.createElement('script');
        script.src = url;
        script.async = true;
        script.crossOrigin = 'anonymous';
        document.body.appendChild(script);
    }

    public render(): JSX.Element | null {
        return this.props.renderView(this.props);
    }
}

export default PvaChatConnector;
