/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';
import Chat from './helpers/chat';
import { IMsdyn365CsChatConnectorData } from './msdyn365-cs-chat-connector.data';
import { IMsdyn365CsChatConnectorProps } from './msdyn365-cs-chat-connector.props.autogenerated';

export interface IMsdyn365CsChatConnectorViewProps extends IMsdyn365CsChatConnectorProps<IMsdyn365CsChatConnectorData> {

}

/**
 *
 * Msdyn365CsChatConnector component
 * @extends {React.PureComponent<IMsdyn365CsChatConnectorProps<IMsdyn365CsChatConnectorData>>}
 */
class Msdyn365CsChatConnector extends React.PureComponent<IMsdyn365CsChatConnectorProps<IMsdyn365CsChatConnectorData>> {
    public componentDidMount(): void {
        window.addEventListener('lcw:error', (errorEvent: object) => {
            // Handle LiveChat SDK error event
            this.props.telemetry.error('lcw:error', errorEvent);
        });
        this._handleChat().catch(e => this.props.telemetry.error(e));
    }

    public render(): JSX.Element | null {
        // console.log('#####', this.props, '#####');
        return this.props.renderView(this.props);
    }

    /**
     * Checks if proactive chat should be triggered, starts the chat and sets context
     */
    private async _handleChat(): Promise<void> {
        const chat = new Chat(this.props);
        await chat.run();
    }
}

export default Msdyn365CsChatConnector;
